/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import clase_base_datos.Conexion_sql;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author g.torrealba
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public Login() {
        initComponents();
        setTitle("Inicio de sesion");
        setSize(600, 650);
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelRound1 = new prueba_diseño.PanelRound();
        t_login_contraseña = new javax.swing.JPasswordField();
        panelRound2 = new prueba_diseño.PanelRound();
        t_login_usuario1 = new javax.swing.JTextField();
        panelRound3 = new prueba_diseño.PanelRound();
        b_login_ingresar = new javax.swing.JLabel();
        e_login_icon_inicio = new javax.swing.JLabel();
        panelRound4 = new prueba_diseño.PanelRound();
        e_login_usuario = new javax.swing.JLabel();
        panelRound5 = new prueba_diseño.PanelRound();
        e_login_contraseña = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(36, 22, 74));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Inicio de Sesión");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 310, -1));

        panelRound1.setBackground(new java.awt.Color(0, 102, 102));
        panelRound1.setRoundBottomLeft(40);
        panelRound1.setRoundBottomRight(40);
        panelRound1.setRoundTopLeft(40);
        panelRound1.setRoundTopRight(40);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t_login_contraseña.setBackground(new java.awt.Color(0, 102, 102));
        t_login_contraseña.setFont(new java.awt.Font("Serif", 0, 10)); // NOI18N
        t_login_contraseña.setForeground(new java.awt.Color(255, 255, 255));
        t_login_contraseña.setText("jPasswordField1");
        t_login_contraseña.setBorder(null);
        panelRound1.add(t_login_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 2, 280, 35));

        jPanel1.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 300, 40));

        panelRound2.setBackground(new java.awt.Color(0, 102, 102));
        panelRound2.setRoundBottomLeft(40);
        panelRound2.setRoundBottomRight(40);
        panelRound2.setRoundTopLeft(40);
        panelRound2.setRoundTopRight(40);
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t_login_usuario1.setBackground(new java.awt.Color(0, 102, 102));
        t_login_usuario1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        t_login_usuario1.setForeground(new java.awt.Color(255, 255, 255));
        t_login_usuario1.setText("jTextField1");
        t_login_usuario1.setBorder(null);
        panelRound2.add(t_login_usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 2, 280, 35));

        jPanel1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 300, 40));

        panelRound3.setBackground(new java.awt.Color(0, 102, 102));
        panelRound3.setRoundBottomLeft(40);
        panelRound3.setRoundBottomRight(40);
        panelRound3.setRoundTopLeft(40);
        panelRound3.setRoundTopRight(40);
        panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b_login_ingresar.setBackground(new java.awt.Color(0, 102, 102));
        b_login_ingresar.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        b_login_ingresar.setForeground(new java.awt.Color(234, 234, 234));
        b_login_ingresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b_login_ingresar.setText("   Ingresar");
        panelRound3.add(b_login_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 50));

        e_login_icon_inicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        e_login_icon_inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tarjeta-de-direccion (1).png"))); // NOI18N
        panelRound3.add(e_login_icon_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jPanel1.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 160, 50));

        panelRound4.setBackground(new java.awt.Color(255, 255, 255));
        panelRound4.setRoundBottomLeft(60);
        panelRound4.setRoundBottomRight(60);
        panelRound4.setRoundTopLeft(60);
        panelRound4.setRoundTopRight(60);
        panelRound4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        e_login_usuario.setBackground(new java.awt.Color(255, 255, 255));
        e_login_usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        e_login_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario (3).png"))); // NOI18N
        panelRound4.add(e_login_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jPanel1.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 40, 40));

        panelRound5.setBackground(new java.awt.Color(255, 255, 255));
        panelRound5.setRoundBottomLeft(60);
        panelRound5.setRoundBottomRight(60);
        panelRound5.setRoundTopLeft(60);
        panelRound5.setRoundTopRight(60);
        panelRound5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        e_login_contraseña.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        e_login_contraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        e_login_contraseña.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelRound5.add(e_login_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jPanel1.add(panelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 40, 40));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/computadora (1).png"))); // NOI18N
        jLabel4.setText("Departamento de tecnología y comumicación");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 560, 320, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b_login_ingresar;
    private javax.swing.JLabel e_login_contraseña;
    private javax.swing.JLabel e_login_icon_inicio;
    private javax.swing.JLabel e_login_usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private prueba_diseño.PanelRound panelRound1;
    private prueba_diseño.PanelRound panelRound2;
    private prueba_diseño.PanelRound panelRound3;
    private prueba_diseño.PanelRound panelRound4;
    private prueba_diseño.PanelRound panelRound5;
    private javax.swing.JPasswordField t_login_contraseña;
    private javax.swing.JTextField t_login_usuario1;
    // End of variables declaration//GEN-END:variables
}
