/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import clase_base_datos.Conexion_sql;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author g.torrealba
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public Login() {
        initComponents();
        setSize(600, 650);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        b_login_inicio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t_login_usuario = new javax.swing.JTextField();
        t_login_contraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b_login_inicio.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        b_login_inicio.setText("Ingresar");
        b_login_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_login_inicioActionPerformed(evt);
            }
        });
        jPanel1.add(b_login_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 230, 50));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("usuario:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("contraseña:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Inicio de Sesión");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 190, -1));
        jPanel1.add(t_login_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 270, 30));
        jPanel1.add(t_login_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 270, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_login_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_login_inicioActionPerformed
        String usuario = t_login_usuario.getText().trim();
        String contraseña = t_login_contraseña.getText().trim();
        String consulta = "select nombre_usuario, contraseña, permiso from usuarios where nombre_usuario = '" + usuario
                + "' and contraseña = '" + contraseña + "'";

        if (!usuario.equals("") || !contraseña.equals("")) {

            try {
                Connection cn = Conexion_sql.conectar();
                PreparedStatement pst = cn.prepareStatement(consulta);
                ResultSet rs = pst.executeQuery();

                if (rs.next()) {
                    String usuarioBD = rs.getString("nombre_usuario");
                    String contraseñaBD = rs.getString("contraseña");
                    int permisoBD = rs.getInt("permiso");

                    if (usuario.equals(usuarioBD) && contraseña.equals(contraseñaBD)) {

                        if (permisoBD == 0) {
                            Administrador adm = new Administrador();
                            adm.setVisible(true);
                            dispose();

                        } else if (permisoBD == 1) {
                            Tecnico tec = new Tecnico();
                            tec.setVisible(true);
                            dispose();
                            
                        } else {
                            Capturista cap = new Capturista();
                            cap.setVisible(true);
                            dispose();
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "Ingreso un dato incorrecto");
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrecto");

                }
            } catch (Exception e) {
                System.err.println(e);
                JOptionPane.showMessageDialog(null, "Error al conectar con la base de datos");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos");
        }

    }//GEN-LAST:event_b_login_inicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_login_inicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField t_login_contraseña;
    private javax.swing.JTextField t_login_usuario;
    // End of variables declaration//GEN-END:variables
}
